[package]
name = "codelst"
version = "2.0.2"
entrypoint = "codelst.typ"
authors = ["Jonas Neugebauer"]
license = "MIT"
description = "A typst package to render sourcecode."
repository = "https://github.com/jneug/typst-codelst"
compiler = "0.12.0"
exclude = ["example.typ", "example.pdf", "manual.pdf", "manual.typ", "tbump.toml"]
categories = ["components", "layout"]
disciplines = ["computer-science", "mathematics", "education", "linguistics"]
keywords = ["sourcecode", "code", "syntax-highlighting", "raw", "line numbers"]

